In [1]:
import numpy as np

# Function to check if a number can be placed in a given cell
def is_valid(board, row, col, num):
    # Check row
    if num in board[row]:
        return False
    
    # Check column
    if num in board[:, col]:
        return False
    
    # Check 3x3 box
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    if num in board[start_row:start_row+3, start_col:start_col+3]:
        return False
    
    return True

# Backtracking function to solve Sudoku
def solve_sudoku(board):
    empty_cells = [(r, c) for r in range(9) for c in range(9) if board[r, c] == 0]
    
    def backtrack(index):
        if index == len(empty_cells):
            return True  # Solution found
        
        row, col = empty_cells[index]
        for num in range(1, 10):
            if is_valid(board, row, col, num):
                board[row, col] = num
                if backtrack(index + 1):
                    return True
                board[row, col] = 0  # Undo assignment
        
        return False
    
    backtrack(0)
    return board

# Example Sudoku puzzle (0 represents empty cells)
sudoku_puzzle = np.array([
    [0, 0, 3, 0, 2, 0, 6, 0, 0],
    [9, 0, 0, 3, 0, 5, 0, 0, 1],
    [0, 0, 1, 8, 0, 6, 4, 0, 0],
    [0, 0, 8, 1, 0, 2, 9, 0, 0],
    [7, 0, 0, 0, 0, 0, 0, 0, 8],
    [0, 0, 6, 7, 0, 8, 2, 0, 0],
    [0, 0, 2, 6, 0, 9, 5, 0, 0],
    [8, 0, 0, 2, 0, 3, 0, 0, 9],
    [0, 0, 5, 0, 1, 0, 3, 0, 0]
])

# Solve the puzzle
solved_board = solve_sudoku(sudoku_puzzle)
print("Solved Sudoku:")
print(solved_board)


Solved Sudoku:
[[4 8 3 9 2 1 6 5 7]
 [9 6 7 3 4 5 8 2 1]
 [2 5 1 8 7 6 4 9 3]
 [5 4 8 1 3 2 9 7 6]
 [7 2 9 5 6 4 1 3 8]
 [1 3 6 7 9 8 2 4 5]
 [3 7 2 6 8 9 5 1 4]
 [8 1 4 2 5 3 7 6 9]
 [6 9 5 4 1 7 3 8 2]]


In [5]:
import numpy as np

def is_safe(board, row, col, n):
    # Check column
    for i in range(row):
        if board[i] == col or \
           board[i] - i == col - row or \
           board[i] + i == col + row:
            return False
    return True

def solve_n_queens(n, row=0, board=None):
    if board is None:
        board = [-1] * n  # Track column position of queens
    
    if row == n:
        return board  # Solution found
    
    for col in range(n):
        if is_safe(board, row, col, n):
            board[row] = col
            result = solve_n_queens(n, row + 1, board)
            if result:
                return result  # Propagate solution upwards
            board[row] = -1  # Backtrack
    
    return None  # No solution found

# Run the algorithm and print the solution
solution = solve_n_queens(8)
if solution:
    print("Solution Found:")
    for r in range(8):
        row_str = ["Q" if solution[r] == c else "-" for c in range(8)]
        print(" ".join(row_str))
else:
    print("No solution found.")


Solution Found:
Q - - - - - - -
- - - - Q - - -
- - - - - - - Q
- - - - - Q - -
- - Q - - - - -
- - - - - - Q -
- Q - - - - - -
- - - Q - - - -
